parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    ECorp\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    ECorp\UI\:
        resource: '../src/UI/*'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    ECorp\Application\User\Command\UserRegisterCommandHandler:
        arguments: ['@PurpleClouds\Infrastructure\Persistence\Repository\UserDbRepository', '@PurpleClouds\Infrastructure\Persistence\Doctrine\Dbal\DbalUserQuery','@PurpleClouds\Infrastructure\Persistence\Repository\UserAggregateRootRepository']

    ECorp\Application\User\Command\UserDeleteCommandHandler:
        arguments: ['@PurpleClouds\Infrastructure\Persistence\Repository\UserDbRepository', '@PurpleClouds\Infrastructure\Persistence\Doctrine\Dbal\DbalUserQuery']


    ECorp\Infrastructure\CommandBus\CommandBus:
        calls:
            - [registerHandler, ['PurpleClouds\Application\User\Command\UserRegisterCommand', '@PurpleClouds\Application\User\Command\UserRegisterCommandHandler']]
            - [registerHandler, ['PurpleClouds\Application\User\Command\UserDeleteCommand', '@PurpleClouds\Application\User\Command\UserDeleteCommandHandler']]
