FROM php:7.4-fpm-alpine

RUN apt-get update && apt-get install -y libpq-dev git unzip zlib1g-dev libzip-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libonig-dev
RUN apk add --no-cache $PHPIZE_DEPS && \
    docker-php-ext-install bcmath pdo pdo_pgsql zip opcache && \
    docker-php-ext-enable bcmath pdo pdo_pgsql zip opcache && \
    pecl install -o -f redis && \
    rm -rf /tmp/pear && \
    echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini

RUN  mkdir -p /var/www/html/var/log/

COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker/php/php-fpm-pool.conf /etc/php7/php-fpm.d/www.conf

RUN pecl install xdebug
RUN docker-php-ext-enable --ini-name xdebug.ini xdebug
RUN { \
    echo 'xdebug.remote_enable=On'; \
    echo 'xdebug.remote_autostart=Off'; \
    echo 'xdebug.idekey=PHPSTORM'; \
    echo 'xdebug.remote_connect_back=On'; \
} >> /usr/local/etc/php/conf.d/xdebug.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer warn=no
