FROM php:7.4-fpm-alpine

RUN set -ex
RUN apk add --no-cache \
    $PHPIZE_DEPS \
    postgresql-dev && \
    docker-php-ext-install bcmath && \
    docker-php-ext-enable bcmath && \
    docker-php-ext-install pdo pdo_pgsql && \
    docker-php-ext-enable pdo pdo_pgsql && \
    docker-php-ext-install opcache && \
    docker-php-ext-enable opcache && \
    rm -rf /tmp/pear

RUN  mkdir -p /var/www/html/var/log/

COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker/php/php-fpm-pool.conf /etc/php7/php-fpm.d/www.conf

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer warn=no

RUN pecl install xdebug
RUN docker-php-ext-enable --ini-name xdebug.ini xdebug
RUN { \
    echo 'xdebug.remote_enable=On'; \
    echo 'xdebug.remote_autostart=Off'; \
    echo 'xdebug.idekey=PHPSTORM'; \
    echo 'xdebug.remote_connect_back=On'; \
} >> /usr/local/etc/php/conf.d/xdebug.ini
