doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '10.4'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        types:
          uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          ECorp:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Idp/Entity'
                prefix: 'ECorp\Infrastructure\Persistence\Idp\Entity'
                alias: EC orp
