framework:
    secret: '%env(APP_SECRET)%'
    session:
        name: ecorp
#        cookie_path: 'http://localhost:8000/'
        handler_id: 'session.handler.native_file'
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true

    templating:
        hinclude_default_template:  ~
        form:
            resources:
                - FrameworkBundle:Form
        cache: ~
        engines:
            - twig
        loaders: []
