security:
  providers:
    users:
      id: 'ECorp\Infrastructure\Security\User\PurpleCloudsUserProvider'

  encoders:
    ECorp\Infrastructure\Persistence\Idp\Entity\User:
      algorithm: bcrypt
    ECorp\Infrastructure\Security\User\SecurityUser:
      algorithm: bcrypt

  firewalls:

    main:
      anonymous: ~
      logout:
        path: web_logout_user

      form_login:
        login_path: web_login_user
        use_referer: true

      provider: users
      guard:
        authenticators:
          - ECorp\Infrastructure\Security\TokenAuthenticator
          - ECorp\Infrastructure\Security\LoginFormAuthenticator
        entry_point: web_login_user

    oauth_token:
      pattern: ^/oauth/v2/token
      security: false

    oauth_authorize:
      pattern: ^/oauth/v2/auth|^/auth/login
      form_login:
        provider: users
        login_path: web_login_user
        check_path: web_login_user
        use_referer: true

  access_control:
    - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
