security:
  providers:
    users:
#      entity:
#        class: 'ECorp\Infrastructure\Persistence\Idp\Entity\User'
#        property: 'email'
      id: 'ECorp\Infrastructure\Security\User\PurpleCloudsUserProvider'
#        property: email

  encoders:
    ECorp\Infrastructure\Persistence\Idp\Entity\User:
      algorithm: bcrypt
    ECorp\Infrastructure\Security\User\SecurityUser:
      algorithm: bcrypt

  firewalls:

    main:
      anonymous: ~
      logout:
        path: web_logout_user

      form_login:
        use_referer: true
        login_path: web_login_user

      provider: users
      guard:
        authenticators:
          - ECorp\Infrastructure\Security\TokenAuthenticator
          - ECorp\Infrastructure\Security\LoginFormAuthenticator
        entry_point: web_login_user

  access_control:
    - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
