version: '3'
services:
  php:
    container_name: ecorp-php
    links:
      - postgres
    build: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    container_name: ecorp-nginx
    image: nginx:stable
    ports:
      - 85:80
    links:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres
    container_name: ecorp-postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecorp-company