version: '3'
services:
  ecorp_purple_clouds_php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile-dev
    links:
      - ecorp_purple_clouds_postgres
    volumes:
      - .:/var/www/html
    networks: ["purple_clouds_network_internal"]

  ecorp_purple_clouds_nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    depends_on:
      - ecorp_purple_clouds_php
    links:
      - ecorp_purple_clouds_php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

  ecorp_purple_clouds_postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: idp_purpleclouds
    networks: ["purple_clouds_network_internal"]

  ecorp_puruple_clouds_assets:
    image: nginx:latest
    ports:
      - 8800:8800
    volumes:
      - ./public/assets:/static/assets
      - ./docker/assets/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

networks:
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
