version: '3.9'
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile-dev
    links:
      - postgres
    volumes:
      - .:/var/www/html
    networks: ["purple_clouds_network_internal"]

  nginx:
    image: nginx:stable
    ports:
      - "8100:8100"
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

  postgres:
    restart: always
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: idp
    networks: [ "purple_clouds_network_internal" ]

  assets:
    image: nginx:stable
    ports:
      - "8800:8800"
    volumes:
      - ./public/assets:/static/assets
      - ./docker/assets/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

volumes:
  pgdata:

networks:
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
