version: '3'
services:
  purple_clouds_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-dev
    links:
      - purple_clouds_postgres
    volumes:
      - .:/var/www/html
    networks: ["default", "purple_clouds_network"]

  purple_clouds_nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    depends_on:
      - purple_clouds_php
    links:
      - purple_clouds_php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["default", "purple_clouds_network"]

  purple_clouds_postgres:
    image: postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: idp_purpleclouds
    networks: ["default", "purple_clouds_network"]

networks:
  purple_clouds_network: {"external": {"name": "purple_clouds_network"}}
