version: '3'
services:
  purple_clouds_php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    links:
      - purple_clouds_postgres
    volumes:
      - .:/var/www/html

  purple_clouds_nginx:
    image: nginx:stable
    ports:
      - 80:80
    depends_on:
      - purple_clouds_php
    links:
      - purple_clouds_php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  purple_clouds_postgres:
    image: postgres
    container_name: ecorp-postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: purpleclouds