users_count:
  path: /api/users/count
  controller: ECorp\UI\Api\UserController:countUsers
  methods: ['GET']

api_list_all_users:
  path: /api/users
  controller: ECorp\UI\Api\UserController::listUsers
  methods: ['GET']

web_login_user:
  path: /auth/login
  controller: ECorp\UI\Frontend\IdpController:login
  methods: ['GET', 'POST']

web_logout_user:
  path: /logout
  methods: ['GET']

idp_profile:
  path: /profile
  controller: ECorp\UI\Frontend\IdpController:profile
  methods: ['GET', 'POST']

idp_profile_client:
  path: /profile/client
  controller: ECorp\UI\Frontend\IdpController:client
  methods: ['GET', 'POST']

idp_profile_user:
  path: /profile/user
  controller: ECorp\UI\Frontend\IdpController:user
  methods: ['GET']

idp_profile_granted_applications:
  path: /profile/applications
  controller: ECorp\UI\Frontend\IdpController:grantedApplications
  methods: ['GET', 'POST']

get_user_by_uuid:
  path: /api/users/{uuid}
  controller: ECorp\UI\Api\UserController:getUserByUuid
  methods: ['GET']

homepage:
  path: /
  controller: ECorp\UI\Frontend\IdpController:homepage
  methods: ['GET']
