api_show_all_users:
    path: /api/users
    controller: ECorp\UI\Api\UserController::listUsers
    methods: ['GET']

register_user:
    path: /api/user
    controller: ECorp\UI\Api\UserController::registerUser
    methods: ['POST']