users_count:
  path: /api/users/count
  controller: PurpleClouds\UI\Api\UserController:countUsers
  methods: ['GET']

api_list_all_users:
  path: /api/users
  controller: PurpleClouds\UI\Api\UserController::listUsers
  methods: ['GET']

get_user_by_uuid:
  path: /api/users/{uuid}
  controller: PurpleClouds\UI\Api\UserController:getUserByUuid
  methods: ['GET']

homepage:
  path: /
  controller: PurpleClouds\UI\Framework\HomepageController:homepage
  methods: ['GET']
