fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

read:
    resource: 'routes/user_read_model.yml'

write:
    resource: 'routes/user_write_model.yml'
