---
- hosts: vb
  become: true
  tasks:
  - name: Ping the the hosts
    ping: ~

  - name: Install aptitude
    apt:
      name: aptitude
      state: latest

  - name: Update APT Reporistory
    apt:
      state: present
      update_cache: true
      force: yes
      allow_unauthenticated: yes

  - name: Upgrade available packages
    apt:
      upgrade: dist

  - name: Remove old docker versions
    apt:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

  - name: Install required docker packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

  - name: Add docker GPG key
    shell: |
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      exit 0

  - name: Configure Docker's APT repository
    apt_repository:
      repo: "{{ docker__apt_repository }}"
      update_cache: true
    vars:
      docker__apt_repository: >
        deb [arch=amd64]
        https://download.docker.com/linux/debian
        stretch stable

  - name: Install Docker
    apt:
      name: "{{docker_version}}"
    vars:
      docker_version:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Create Docker configuration directories
    file:
      path: "{{ item }}"
      state: "directory"
      owner: "root"
      group: "root"
      mode: "0755"
    with_items:
      - "/etc/docker"
      - "/etc/systemd/system/docker.service.d"

  - name: Get docker host IP
    shell: ip -4 addr show docker0 | awk 'NR==2 {print $2}' | sed 's/[/].*$//'
    register: docker_host_ip
    until: docker_host_ip.stdout != ""
    retries: 10
    delay: 30


